export const GET_TRACKS_STARTED = 'GET_TRACKS_STARTED';
export const GET_TRACKS_COMPLETED = 'GET_TRACKS_COMPLETED';
export const GET_TRACKS_FAILED = 'GET_INITIAL_TRACKS_FAILED';
export const SET_SELECTED_TRACK = 'SET_SELECTED_TRACK';
